version: 0.1

# Notes: ARN references within the associated SAM template to some resources are defined
# by naming convention, not by Reference, to avoid circular references. GovCloud ARNs use
# a different scheme name 'aws-us-gov' instead of 'aws'.
# For example, a reference to an ALB Target Group in commercial (local) deployment is:
# arn:aws:elasticloadbalancing:${AWS::Region}:${AWS::AccountId}:targetgroup/project-cies-doc-local/*
# whereas in the GovCloud dev deployment it becomes:
# arn:aws-us-gov:elasticloadbalancing:${AWS::Region}:${AWS::AccountId}:targetgroup/project-cies-doc-dev/*
#
# ALBVisibility determines whether the ALB is internet facing or only accessible from a VPC. For all deployment
# except for local testing this value MUST be 'internal'. For 'local' deployment the value may be internet-facing,
# in which case adding WAF that restricts access to only the developer IP to the ALB is highly recommended. External
# IPs in the AWS range will be probed within minutes of endpoint creation.

dev:
    deploy:
        parameters:
            resolve_s3: false
            capabilities: CAPABILITY_IAM
            confirm_changeset: true
            s3_prefix: 'spi-ocr-app-dev'
            disable_rollback: false
            parameter_overrides:
            - LogLevel=DEBUG
            - stage=dev
            - subnets=subnet-93aac8cf,subnet-0723de9a5e38a2cdf
            - networkInterfaceSubnet=subnet-93aac8cf
            - ALBVisibility=internet-facing
            - ARNScheme=aws
            - AlbServiceRoleAccount=127311923021
            - VPC=vpc-94fb46ee
            
preprod:
    deploy:
        parameters:
            resolve_s3: false
            capabilities: CAPABILITY_IAM
            confirm_changeset: true
            s3_prefix: 'spi-ocr-app-preprod'
            disable_rollback: false
            parameter_overrides:
            - LogLevel=INFO
            - stage=prprd
            - subnets=subnet-0ffcf91a8634ae2c6,subnet-054227598f4a06140
            - networkInterfaceSubnet=subnet-0ffcf91a8634ae2c6
            - ALBVisibility=internal
            - ARNScheme=aws
            - AlbServiceRoleAccount=190560391635
            - VPC=vpc-06dbfd655b53de4a8
            
prod:
    deploy:
        parameters:
            resolve_s3: false
            capabilities: CAPABILITY_IAM
            confirm_changeset: true
            s3_prefix: 'spi-ocr-app-prod'
            disable_rollback: false
            parameter_overrides:
            - LogLevel=WARN
            - stage=prod
            - subnets=subnet-0505255c5fca62d8a,subnet-027cdb68d9594cb6a
            - networkInterfaceSubnet=subnet-0505255c5fca62d8a
            - ALBVisibility=internal
            - ARNScheme=aws
            - AlbServiceRoleAccount=190560391635
            - VPC=vpc-08f3d1c2c27f5f43f

# Following this point are configurations for developer local environment.
default:
    deploy:
        parameters:
            resolve_s3: false
            capabilities: CAPABILITY_IAM
            confirm_changeset: true
            stack_name: 'spi-ocr-app-local'
            s3_prefix: 'spi-ocr-app-local'
            disable_rollback: false
            parameter_overrides:
            - stage=local
            - LogLevel=DEBUG
            - subnets=subnet-93aac8cf,subnet-0723de9a5e38a2cdf
            - networkInterfaceSubnet=subnet-93aac8cf
            - ALBVisibility=internet-facing
            - ARNScheme=aws
            - AlbServiceRoleAccount=127311923021
            - VPC=vpc-94fb46ee
