name: BIPP_Preproduction_deployment
on:
  merge_group:
    branches:
      - main

# prevents multiple instances of this workflow from running
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Tag the build with the git commit sha
      - run: git rev-parse HEAD > .GIT_SHA
      - run: cat .GIT_SHA

      # sam validate
      - run: sam validate --config-env ctb

      # sam build 
      - run: sam build --use-container --config-env ctb

      # Run Unit tests- Specify unit tests here 

      # sam deploy
      - run: sam deploy --config-env prod --no-confirm-changeset --no-fail-on-empty-changeset --stack-name cies-bipp-prod --s3-bucket cies-bipp-deployment_prod --capabilities CAPABILITY_IAM --region us-east-1 --on-failure ROLLBACK
