on:
  push:
    branches-ignore:
      - main

# prevents multiple instances of this workflow on the same ref(branch) from running
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      # sam build 
      - run: sam build --use-container --config-env ctb

      # Run Unit tests- Specify unit tests here 
      #- run: pytest

      # Use SAM to deploy BIPP
      # NOTE: the parameter overrides use Github Action Variables, go to /settings/variables/actions from the
      # root of the Github project.
      # The Github Action Variables are also environment specific, enforced by a naming convention.
      # i.e. in "AWS_DEFAULT_VPC_ID" the environment is "DEFAULT", the equivalent for PROD would be "AWS_PROD_VPC_ID"
      # The DEFUALT values are used for the 'dev' environment(s), PRPRD and PROD are both specific to their respective environments
      - run: "sam deploy --config-env dev --no-confirm-changeset --no-fail-on-empty-changeset --stack-name cies-bipp-dev --s3-bucket cies-bipp-deployment-dev --capabilities CAPABILITY_IAM --region us-east-1 --on-failure ROLLBACK --parameter-overrides VPC=${{vars.AWS_DEFAULT_VPC_ID}} AlbServiceRoleAccount=${{vars.AWS_DEFAULT_SERVICE_ACCOUNT_ID}} subnets=${{vars.AWS_DEFAULT_SUBNETS}} networkInterfaceSubnet=${{vars.AWS_DEFAULT_NETWORK_INTERFACE_SUBNET}}"

      # if: ${{ env.DAY_OF_WEEK == 'Monday' }}
      # run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
      # Run Integration tests- Specify unit tests here

      # sam delete, this removes the entire environment after integration testing is complete
      #- run: sam delete --config-env ctb --no-confirm-changeset --stack-name cies-bipp-local --region us-east-1
