on:
  push:
    branches-ignore:
      - main

# prevents multiple instances of this workflow on the same ref(branch) from running
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      # sam build 
      - run: sam build --use-container --config-env ctb

      # Run Unit tests- Specify unit tests here 
      #- run: pytest

      # sam deploy
      - run: sam deploy --config-env dev --no-confirm-changeset --no-fail-on-empty-changeset --stack-name cies-bipp-dev --s3-bucket cies-bipp-deployment-dev --capabilities CAPABILITY_IAM --region us-east-1 --on-failure ROLLBACK

      # Run Integration tests- Specify unit tests here

      # sam delete, this removes the entire environment after integration testing is complete
      #- run: sam delete --config-env ctb --no-confirm-changeset --stack-name cies-bipp-local --region us-east-1
